sonar.projectKey=Solierrr_ai-operational
sonar.organization=solierrr
sonar.python.version=3.14

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
